config/routes.rb
Journalofgood::Application.routes.draw do
  resources :invitations, only: [:index, :create]

  resources :confirmations, only: [:edit, :update]

  resource :password, only: [:edit, :update]

  resources :entries, except: [:new]
  
  resources :password_reset_emails, only: [:new, :create]

  resources :contacts, only: [:new, :create]

  get 'sessions/new' => 'sessions#new'

  get 'sessions' => 'sessions#show'
  
  post 'sessions' =>'sessions#create'

  delete 'sessions' =>'sessions#destroy' #later change to a destory

  get 'journals/:journal', to: 'entries#journal', as: :journal
  
  get 'statics/about' => 'statics#about'
  
  root 'entries#all'
  
  mount Monologue::Engine, at: '/blog' # or whatever path, be it "/blog" or "/monologue"
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  has_paper_trail :only => [:content]
  acts_as_taggable_on :journals
  self.per_page = 10
  validates :content, presence: true
  validate :entry_limit
  def entry_limit
    if Entry.where(:user_id => user_id, :created_at => ((Time.now - 1.day)..Time.now)).size > 20
      errors[:base] << "You have exceeded the rate at which you can create entries!"
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:journal, :all]
  before_action :default_page, only: [:index,:journal,:all]
  # GET /entries
  # GET /entries.json
  def index
    @entry = Entry.new(:anonymous => true, :publish=>false)
    @entries = Entry.where(user_id: session[:user_id]).order(id: :desc).paginate(:page => params[:page])
  end

  def journal
    @entries = Entry.where(publish: true).tagged_with(params[:journal], :on => :journals).order(id: :desc).paginate(:page => params[:page])
  end
  
  def all
    @entries = Entry.where(publish: true).order(id: :desc).paginate(:page => params[:page])
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    @entry.user_id = session[:user_id]
    if @entry.save
      redirect_to @entry, notice: 'Entry was successfully created.'
    else
      @entries = Entry.where(user_id: session[:user_id]).order(id: :desc).paginate(:page => params[:page])
      render action: 'index'
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    redirect_to entries_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
    if @entry.user_id != session[:user_id]
      render :text => 'Not Found', :status => '404'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def entry_params
    params.require(:entry).permit(:content, :anonymous, :journal_list, :publish)
  end
  
  def default_page
    params[:page] = 1 unless params[:page]
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div class="row">
		<div class="col-md-2 text-right">
			<% unless local_assigns[:date].nil?%>
				<h4>
					<%=date.to_formatted_s(:rfc822) %>
				</h4>
			<%end%>
		</div>
		<div class="col-md-8">
			<div class="entry">
				<blockquote>
					<p>
						<%= entry.content %>
					</p>
					<footer>
						<% if entry.anonymous%>
						Anonymous
						<% else %>
						<%= entry.user.name%>
						<% end %>
						<%= "in journals" unless entry.journal_list.empty? %>
						<% entry.journal_list.each do |journal| %>
						<%= link_to journal,controller: "entries", action: "journal", journal: journal %>
						<% end%>

						<br/>
						<% if entry.user_id == session[:user_id] and show_actions%>
						  <%= link_to 'Edit', edit_entry_path(entry)%>
						  <%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
						<%end%>
					</footer>
				</blockquote>
			</div>
		</div>
		<div class="col-md-2"></div>

	</div>

app/views/entries/_form.html.erb
<div class="row">
	<div class="col-sm-1 col-md-2"></div>
	<div class="col-sm-10 col-md-8">
		<%= form_for(@entry) do |f| %>
		<% if @entry.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @entry.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="field">
			<%= f.text_area :content , class:"form-control", rows:4,placeholder: "Write down your good deed!"%>
		</div>
		<br/>
		<div class="field">
			<%= f.text_field :journal_list , class:"form-control",placeholder: "Comma separated list of journals"%>
		</div>
		<br/>
		<div class="row">
			<div class="col-xs-4">
				<label> <%= f.check_box :anonymous %>
					Anonymous </label>
			</div>
			<div class="col-xs-4">
				<label> <%= f.check_box :publish %>
					Publish </label>
			</div>
			<div class="actions col-xs-4" >
				<%= f.submit "Save Entry", class:"btn btn-md btn-primary pull-right" %>
			</div>
		</div>
		<% end %>
	</div>
	<div class="col-sm-1 col-md-2"></div>
</div>

app/views/entries/_paginate.html.erb
<div class="row">
	<div class="col-sm-1 col-md-2"></div>
	<div class="col-sm-10 col-md-8">
		<%= will_paginate @entries %>
	</div>
	<div class="col-sm-1 col-md-2"></div>
</div>

app/views/entries/all.html.erb
<div class="container">
	<% if notice%>
	<div class="alert alert-info">
		<%= notice%>
	</div>
	<% end%>
	<%= render partial: "paginate"%>
	<%
	dates = Set.new
	@entries.each do |entry|
	  if dates.include?(entry.created_at.to_date) %>
		<%= render partial: "entry", locals:{entry:entry, show_actions:false}%>
  	  <% else
	  	dates << entry.created_at.to_date %>
	  	<%= render partial: "entry", locals:{entry:entry, show_actions:false, date:entry.created_at.to_date }%>
	  <% end%>
	<% end %>
	<%= render partial: "paginate"%>
</div>

app/views/entries/edit.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/entries/index.html.erb
<div class="container">
	<%= render 'form' %>
	</br>
	<%= render partial: "paginate"%>
	<%
	dates = Set.new
	@entries.each do |entry|
	  if dates.include?(entry.created_at.to_date) %>
	  	<%= render partial: "entry", locals:{entry:entry, show_actions:true}%>
	  <% else
	  	dates << entry.created_at.to_date %>
	  	<%= render partial: "entry", locals:{entry:entry, show_actions:true, date:entry.created_at.to_date }%>
	  <% end%>
	<% end %>
	<%= render partial: "paginate"%>
</div>

app/views/entries/journal.html.erb
<div class="container">
	<%= render partial: "paginate"%>
	<%
	dates = Set.new
	@entries.each do |entry|
	  if dates.include?(entry.created_at.to_date) %>
		<%= render partial: "entry", locals:{entry:entry, show_actions:false}%>
  	  <% else
	  	dates << entry.created_at.to_date %>
	  	<%= render partial: "entry", locals:{entry:entry, show_actions:false, date:entry.created_at.to_date }%>
	  <% end%>
	<% end %>
	<%= render partial: "paginate"%>
</div>

app/views/entries/show.html.erb
<div class="container">
	<% if notice%>
	<div class="alert alert-info">
		<%= notice%>
	</div>
	<% end%>
	<%= render partial: "entry", locals:{entry:@entry, show_actions:true}%>
	<div class="col-sm-1 col-md-2"></div>
	<div class="col-sm-10 col-md-8">
		<%= link_to "Back to My Journal", entries_path%>
	</div>
	<div class="col-sm-1 col-md-2"></div>
</div>